name: Build and Publish Docker

on:
  workflow_call:
  pull_request:
    branches:
      - main
      - v[0-9]+
    paths:
      - .github/workflows/build.yaml
      - eKIBRA.info
      - '**.cs'
      - test/**
      - '!**.md'

concurrency:
  # Terminate all previous runs of the same workflow for pull requests
  group: build-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        # Hack for enabling color output, see:
        # https://github.com/actions/runner/issues/241#issuecomment-842566950
        shell: script -qec "bash --noprofile --norc -eo pipefail {0}"
        
    steps:
      - name: Anchore Scan project
        uses: anchore/scan-action@v6        
        with:
          path: "."
          fail-build: true
          severity-cutoff: critical
          
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.EKIBRA_SSH_KEY }} # uses a preconfigure GitHub SSH
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get commit current eKIBRA.info version
        run: |
          ekibra_version="$(grep -oP '^version:\s*\K.*' eKIBRA.info)"

          if [[ "$ekibra_version" == *.*.* ]]; then
            echo ekibra_version="v$ekibra_version"
          else
            echo ekibra_version="devel"
          fi

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v6
        with:
          push: true
          # tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          tags: ghcr.io/${{ env.REPO }}:${{ env.ekibra_version }}
          file: ./Dockerfile
