name: Continuous Integration

on:  
  push:
    branches:
      - main
      - v[0-9]+
  pull_request:    
    branches:
      - main
      - v[0-9]+

jobs:
  test:
    name: .NET Core Test
    uses: ./.github/workflows/test.yml
  
  docker:
    permissions:
      contents: 'read'
      packages: 'write'

    name: .NET Core Docker
    uses: ./.github/workflows/build.yml      
      
  tag:
    runs-on: ubuntu-latest    
    name: Version Tag
    
    concurrency:
      # Never tag outdated commits on the main branch by skipping superseded commits
      group: ci-tag-${{ (github.ref == 'refs/heads/main' && github.ref) || github.run_id }}
      # TODO: Enable this once https://github.com/orgs/community/discussions/13015 is solved
      cancel-in-progress: false
      
    if: vars.RELEASE_ENABLED

    needs:
      - test
      - docker
    
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.EKIBRA_SSH_KEY }} # uses a preconfigure GitHub SSH
      - name: Tag latest commit
        run: |
          ekibra_version="$(grep -oP '^version:\s*\K.*' eKIBRA.info)"

          if [[ "$ekibra_version" == *.*.* ]]; then
            git fetch --tags

            if [ -z "$(git tag --list "v$ekibra_version")" ]; then
              git tag "v$ekibra_version"
              git push origin "v$ekibra_version"
            fi
          else
            git tag -f "devel"
            git push -f origin "devel"
          fi      