name: Release on Azure

env:
  AZURE_WEBAPP_NAME: "ekibra-web"
  DOTNET_PROJECT_NAME: "eKIBRA.Web"
  
on:
  push:
    tags:
      - devel
      - v*

concurrency:
  # Terminate all previous runs of the same workflow for the same tag.
  group: release-${{ github.ref }}
  # TODO: Enable this once https://github.com/orgs/community/discussions/13015 is solved
  cancel-in-progress: false

permissions:
  contents: 'read'
  packages: 'write'
  
jobs:
  migrate:
    runs-on: ubuntu-latest
    
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Setup EF Tools
        run: |
          dotnet tool install --global dotnet-ef 
          dotnet tool restore 

      - name: Bundle EF Migrations
        run: |
          dotnet ef migrations bundle -r linux-x64 --project ${{ env.DOTNET_PROJECT_NAME }} 

      - name: Upload EF Migrations Bundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: efbundle
          path: ./efbundle

      - name: Download EF Bundle Artifact
        uses: actions/download-artifact@v4
        with:
          name: efbundle
          path: artifacts/efbundle

      - name: Migrate Database
        shell: bash
        run: |
          chmod +x ./artifacts/efbundle/efbundle 
          ./artifacts/efbundle/efbundle --connection "${{ secrets.CONNECTIONSTRINGS__DEFAULTCONNECTION }}"
    
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    needs: migrate
    
    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
          # images: 'ghcr.io/${{ env.REPO }}:${{ github.ref_name }}'

#      - name: GitHub Tag Name example
#        run: |
#          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
#          echo "Tag name from github.ref_name: ${{  github.ref_name }}"            
