name: Check and Test

on:
  workflow_call:

concurrency:
  # Terminate all previous runs of the same workflow for pull requests
  group: test-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    permissions:
      contents: read #This is required for actions/checkout
      
    steps:
      - name: Anchore Scan
        uses: anchore/scan-action@v6
        with:
          path: "."
          fail-build: true
          severity-cutoff: critical
          
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Check Code Formatting
        run: dotnet format --verify-no-changes  
        
#      - name: Build
#        run: dotnet build --no-restore
        
      - name: Test with the dotnet CLI
        run: dotnet test --collect:"XPlat Code Coverage"
        
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}